### PR TITLE
Update netlayer

### PR DESCRIPTION
**Pull request by preland**

### CODE REVIEW

**Comment by preland** [comment]
(This is what my current fork has, once this is fixed up then the repo will be usable in haveno)

**Comment by preland** [comment]
The only issue currently is a dependency on pokkst's tor-binary PR; this could be addressed by creating a repo for tor-binary that integrates the PR (or by getting Bisq to merge the PR, although I'm assuming that isn't preferable for our use case)

**Comment by preland** [comment]
This should now be ready to merge; after it is merged, it would be best to add a new release for this version (otherwise the netlayerVersion in haveno's build.gradle will have to be a commit instead of a proper version number)

Once this is merged, the other PR I am working on should be finished

**Comment by woodser** [comment]
Sorry, I missed these notifications. Starred the repo now. :)

**Comment by woodser** [comment]
[tor-binary](https://github.com/haveno-dex/tor-binary) repo is created and commit from pokkst added.

**Comment by woodser** [comment]
> This should now be ready to merge; after it is merged, it would be best to add a new release for this version (otherwise the netlayerVersion in haveno's build.gradle will have to be a commit instead of a proper version number)

We're using a commit hash in the build.gradle now, so fine to continue using one.

> Once this is merged, the other PR I am working on should be finished

Great, looking forward to it. Thanks.

**Pull request merged**
